feat: try to proxy body even after body-parser middleware
chimurai/http-proxy-middleware pull request #492
Opened 2020-12-31 09:42 UTC by midgleyc

If a body parser middleware is added before the proxy is configured, proxying POST requests with bodies fails. This fixes that and provides a test, as requested by @chimurai in #460.

Code from #460 by @sarumont and from #320 by @repl-chris used -- thanks to both!

Fixes #90
Fixes #320
Fixes #417

2021-04-15 19:08 UTC, dquang-tran commented
Hi, any updates on this PR? Thanks for doing this.

2021-04-18 15:08 UTC, chimurai commented
Thanks @midgleyc for this PR. (Sorry for late reply)

Could you separate `this.fixBody` function to external handler? Similar to `responseInterceptor`'s implementation. https://github.com/chimurai/http-proxy-middleware/tree/master/src/handlers

This'll make `fixBody` optional, since not everyone is having this issue. And it'll prevent bloat in the core functionality.

It's usage will be like this:

```js
const { createProxyMiddleware, fixBody } = require('http-proxy-middleware');

const proxy = createProxyMiddleware({
  /**
   * Fix bodyParser
   **/
  onProxyReq: fixBody,
});
```

Planning to work on a `preset`-like functionality where something like `recommended` contains a collection of handlers for the majority of use-cases.

2021-04-18 15:37 UTC, midgleyc commented
@chimurai Done, how does it look now?

2021-04-18 15:57 UTC, chimurai requested changes
That's quick  :)

Could you add some documentation before of after:
https://github.com/chimurai/http-proxy-middleware/blob/master/README.md#intercept-and-manipulate-responses

2021-04-18 15:57 UTC, chimurai commented on test/e2e/_utils.ts
> +export function createApp(...middleware: RequestHandler[]): Express {
Could you pluralise this to: `...middlewares` ?

2021-04-18 16:03 UTC, chimurai commented on src/handlers/fix-request-body.ts
> +    proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
Can you add this comment to silence DeepCode bot?
```
    // deepcode ignore ContentLengthInCode: bodyParser fix
    proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
```

2021-04-18 17:35 UTC, midgleyc commented
Changes made.

You should be able to make changes to my branch directly, if you'd like.

2021-04-24 12:59 UTC, chimurai approved these changes
lgtm

2021-04-24 13:03 UTC, merged

2021-04-24 13:04 UTC, chimurai commented
Thanks @midgleyc !

2021-04-24 13:06 UTC, midgleyc commented
You're welcome, thanks for merging :)

2024-08-23 11:01 UTC, dhurtrci commented
This workaround doesn't seem to work anymore.
In later versions, the proxyReq etc. are set inside the on property:
```

on: {
                        /**
                        * Fix bodyParser
                        **/
                        proxyReq: fixRequestBody
                    }
```

In such versions, I get an error in the fixRequestBody method (where it sets the content type header), and is says (something like) 'cannot change headers after they are sent to the client'.

2024-08-23 18:33 UTC, chimurai commented
@dhurtrci Can you please open a new issue and provide a reproduction so it can be investigated?