Fix request body for empty JSON object requests
chimurai/http-proxy-middleware pull request #640
Opened 2021-07-14 03:23 UTC by mhassan1

## Description

This PR fixes the `fixRequestBody` utility so that it treats empty object bodies like non-empty object bodies and fixes them, as expected.

## Motivation and Context

The `fixRequestBody` utility contains a check for empty objects that results in early `return`: https://github.com/chimurai/http-proxy-middleware/blob/c9bec81e82664809c816250f15d30543c4447571/src/handlers/fix-request-body.ts#L11-L13

Currently, JSON requests with empty object payloads do not get their request bodies fixed by this utility, and the request to the target hangs while the target waits for a payload that will never arrive.

This PR removes the special handling for empty objects and treats them like any other object.

Resolves https://github.com/chimurai/http-proxy-middleware/issues/639.

## How has this been tested?

I ran the reproduction steps in https://github.com/chimurai/http-proxy-middleware/issues/639 before and after the code change. I also updated automated tests.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-11-11 05:31 UTC, HappyColour commented
This PR has been released right?

2021-11-11 06:39 UTC, eemelipa commented
> This PR has been released right?

I don't think so. The PR is still open and the library doesn't have the fix

2021-11-11 08:56 UTC, HappyColour commented
> > This PR has been released right?
> 
> I don't think so. The PR is still open and the library doesn't have the fix

Thx bro @eemelipa,please confirm this pr has been merged @mhassan1.

2021-11-11 11:01 UTC, mhassan1 commented
No, it is still open.

2021-11-28 11:31 UTC, chimurai commented
Hi @mhassan1. I left a remark in the PR a while ago which hasn't been resolved.

Happy to merge it after it's fixed.

2021-11-28 11:47 UTC, chimurai requested changes

2021-11-28 11:47 UTC, chimurai commented on test/unit/fix-request-body.spec.ts
> -  it('should not write when body is empty', () => {
Instead of combining 2 different cases in 1 test; Think it's better to have 1 test to test for the empty-object and 1 test to test for object with some values.

Can you modify the test: `should not write when body is empty` to test explicitly for the empty object like. I.e.: `should write when body is an empty JSON object`

Don't think you need to touch this test:
`it('should write when body is not empty and Content-Type is application/json'`

2021-11-29 16:13 UTC, mhassan1 commented on test/unit/fix-request-body.spec.ts
> -  it('should not write when body is empty', () => {
Thanks, I've incorporated that feedback.

2021-12-02 11:34 UTC, mhassan1 commented
@chimurai This is ready for re-review.

2022-01-23 15:28 UTC, chimurai approved these changes

2022-01-23 15:29 UTC, merged

2022-01-23 15:29 UTC, chimurai commented
Thanks @mhassan1 !

2022-01-23 17:41 UTC, chimurai commented
published in `http-proxy-middleware@2.0.2`