Update fix-request-body content type check
chimurai/http-proxy-middleware pull request #725
Opened 2022-03-10 08:00 UTC by kevinxh

## Description

It is common for POST request to have the content type: `application/x-www-form-urlencoded; charset=UTF-8`

The `charset` part can be set when you have a form with attribute `accept-charset="utf-8"`

I encountered this while using the `fixRequestBody` function and the content type check doesn't take the charset into account. 

![Screen Shot 2022-03-09 at 11 57 11 PM](https://user-images.githubusercontent.com/10948652/157614824-41064241-56e2-45ec-90ef-ddfa3b71fb64.png)

## Motivation and Context

## How has this been tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-03-10 09:52 UTC, chimurai commented
Hi, thanks for the PR.

Looks like a good improvement.

Could you add a unit-test for this change?
https://github.com/chimurai/http-proxy-middleware/blob/master/test/unit/fix-request-body.spec.ts

2022-03-12 09:48 UTC, chimurai requested changes

2022-03-12 09:48 UTC, chimurai commented on src/handlers/fix-request-body.ts
> +  if (contentType && contentType.includes('application/x-www-form-urlencoded')) {
Could you add a unit-test? Testing what you described in the PR description: `application/x-www-form-urlencoded; charset=UTF-8`

https://github.com/chimurai/http-proxy-middleware/blob/master/test/unit/fix-request-body.spec.ts

2022-03-13 02:55 UTC, kevinxh commented on src/handlers/fix-request-body.ts
> +  if (contentType && contentType.includes('application/x-www-form-urlencoded')) {
👍  unit test is added.

2022-03-13 15:52 UTC, merged

2022-03-13 16:13 UTC, chimurai commented
Thanks for making the PR @kevinxh!

Published fix in [`v2.0.4`](https://www.npmjs.com/package/http-proxy-middleware/v/2.0.4)