fix(utils): fixRequestBody support `multipart/form-data`
chimurai/http-proxy-middleware pull request #877
Opened 2023-02-15 11:05 UTC by JS-mark

## Description

## Motivation and Context

## How has this been tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-02-15 20:29 UTC, chimurai commented
Could you add unit tests in:
https://github.com/chimurai/http-proxy-middleware/blob/master/test/unit/fix-request-body.spec.ts

2023-02-16 02:57 UTC, JS-mark commented
> Could you add unit tests in: https://github.com/chimurai/http-proxy-middleware/blob/master/test/unit/fix-request-body.spec.ts

ok It has been added.

2023-02-17 03:10 UTC, JS-mark reviewed
PTAL

2023-02-20 20:22 UTC, chimurai requested changes

2023-02-20 20:22 UTC, chimurai commented on src/handlers/fix-request-body.ts
> +/**
Please move the `handlerFormDataBodyData` to the bottom of the file.

Please remove the `export` of this private function

2023-02-20 20:22 UTC, chimurai commented on test/unit/fix-request-body.spec.ts
> +import { fixRequestBody, handlerFormDataBodyData } from '../../src/handlers/fix-request-body';
Please remove and avoid testing with private `handlerFormDataBodyData` directly

2023-02-20 20:22 UTC, chimurai commented on test/unit/fix-request-body.spec.ts
> +    const expectedBody = handlerFormDataBodyData('multipart/form-data', body);
Test will always pass if you use the private `handlerFormDataBodyData` function to generate the expectedBody for assertion.

Please use hardcoded values or jest's inline snapshot to assert the `write` call signature.

2023-02-20 20:22 UTC, chimurai commented on test/unit/fix-request-body.spec.ts
> +    const expectedBody = handlerFormDataBodyData('multipart/form-data', body);
Same. Please remove the call to `handlerFormDataBodyData` to generate `expectedBody`

2023-02-20 20:36 UTC, chimurai commented on test/unit/fix-request-body.spec.ts
> +    body.append('someField', 'some value');
`someField` is added, can you add an assertion?

2023-03-11 15:54 UTC, closed without merging